parserOptions:
  ecmaVersion: 8
  sourceType: 'module'
  ecmaFeatures:
    jsx: true
    impliedStrict: true
env: { node: true }
globals: { CONFIG: true, ENV: true, TEST: true, es6: true, Promise: true }
extends: "eslint:recommended"
rules:
  indent:
    - error
    - 2
  semi: error
  no-const-assign: error
  no-var: error
  prefer-const: error
  no-console: off